spring:
  application:
    name: itoken-web-admin-8200
  zipkin:
    base-url: http://www.zikpin7001.com:7001

##从8100开始
server:
  port: 8200

eureka:
  client:
    service-url:
      defaultZone: http://www.eureka8001.com:8001/eureka,http://www.eureka8002.com:8002/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
