spring:
  zipkin:
    base-url: http://www.zikpin7001.com:7001

eureka:
  client:
    service-url:
      defaultZone: http://www.eureka8001.com:8001/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info