spring:
  application:
    name: itoken-eureka-eureka-8002
  zipkin:
    base-url: http://localhost:7001

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8002/eureka
  instance:
    hostname: eureka-8002
    ip-address: true

server:
  port: 8002