#  dev环境
#  application name
spring:
  application:
    name: itoken-zuul
#端口
server:
  port: 6001

zuul:
  routes:
    posts:
      path: /zuul/posts/**
      serviceId: itoken-web-posts
  ignored-services: itoken-web-posts

