spring:
  application:
    name: itoken-server-redis
  zipkin:
    base-url: http://www.zikpin7001.com:7001
  redis:
    lettuce:
      pool:
        max-active: 8
    sentinel:
      master: mymaster
      nodes: 192.168.25.128:26379,192.168.25.128:26380,192.168.25.128:26381

server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://www.eureka8001.com:8001/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info