spring:
  application:
    name: itoken-web-admin
  zipkin:
    base-url: http://www.zikpin7001.com:7001
##从8100开始
server:
  port: 8200

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info