spring:
  application:
    name: itoken-eureka-dev
# 链路追踪
  zipkin:
    base-url: http://www.zikpin7001.com:7001
server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://www.eureka8002.com:8002/eureka
    fetch-registry: true
    register-with-eureka: false
  instance:
    ip-address: true
    hostname: itoken-eureka-dev