#  dev环境
#  application name
spring:
  application:
    name: itoken-zuul
#端口
server:
  port: 6001

#注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka8001.com:8001/eureka
