spring:
  application:
    name: itoken-service-admin-8100-prod
  zipkin:
    base-url: http://www.zikpin7001.com:7001
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 721000
    url: jdbc:mysql://192.168.25.128:3306/abc?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource

##从8100开始
server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://www.eureka8001.com:8001/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

mybatis:
  config-location: classpath:mybatis/MapperConfig.xml

#        配置数据库
