spring:
  application:
    name: itoken-server-redis
  redis:
    lettuce:
      pool:
        max-active: 8
    sentinel:
      master: mymaster
      nodes: 192.168.25.128:26379,192.168.25.128:26380,192.168.25.128:26381
server:
  port: 8101