server:
  port: 8102

spring:
  application:
    name: itoken-service-sso-dev
  #  配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 721000
    url: jdbc:mysql://192.168.25.128:3306/itoken-service-admin?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false    #关闭缓存

hystrix:
  metrics:
    enabled: true

mybatis:
  config-location: classpath:mybatis/MapperConfig.xml

